Post search endpoint
bcgov/ppr-deprecated pull request #280
Opened 2020-01-20 22:30 UTC by jguertin

Created an end-point to handle a POST requests to `/searches`.  This included a few changes including:
- The new "POST" method in the end point
- Addition of commit/rollback around the database dependency
- Implementation of pydantic validators in the schema. Ran into one odd-ball issue here:
  - The validator should act like a class method and doesn't require self.  pylint worked fine on my machine, but failed in Github Actions: https://github.com/vituary-solutions/ppr/runs/399781757
  - To work around this for now, I've added hints for pylint to ignore it
- Updates to the model and repository for creating database objects
- unit and integration tests

2020-01-20 22:34 UTC, jguertin commented on ppr-api/src/schemas/search.py
> +        if values['type'] == SearchType.REGISTRATION_NUMBER.value:
Note: I limited the effort on this to Base Registration search

2020-01-21 00:52 UTC, bryan-gilbert approved these changes

2020-01-21 18:27 UTC, WalterMoar commented on ppr-api/src/endpoints/search.py
> +@router.post("/searches", response_model=schemas.search.Search, response_model_by_alias=False)
I wish we could lint on quotes - we're going single, yes?

2020-01-21 18:29 UTC, WalterMoar commented on ppr-api/tests/unit/schemas/test_search_schema.py
> +        pytest.fail("A validation error was expected since there was no value field in the criteria")
Quotes again.

2020-01-21 18:42 UTC, WalterMoar commented on ppr-api/src/schemas/search.py
> +    def type_must_match_search_type(cls, search_type):  # pylint:disable=no-self-argument
Will the @classmethod annotation prevent the pylint problem?

2020-01-21 18:46 UTC, jguertin commented on ppr-api/src/endpoints/search.py
> +@router.post("/searches", response_model=schemas.search.Search, response_model_by_alias=False)
Yes :(.  I checked into that yesterday, there's a couple of open source tools: `pylint-quotes` and `flake8-quotes`.  Not sure how comfortable I am bringing them in though.  I'm getting better...  nice catch.

2020-01-21 18:46 UTC, WalterMoar requested changes
Some double quotes snuck in.

2020-01-21 18:58 UTC, jguertin commented on ppr-api/src/schemas/search.py
> +    def type_must_match_search_type(cls, search_type):  # pylint:disable=no-self-argument
@validator should be treated as a class method, so adding that decorator would be an equivalent code smell, I think.  I'll add an issue to look into this for tech debt, it that works.

See https://prompt-build--pydantic-docs.netlify.com/#validators for more info on validators

2020-01-21 19:19 UTC, jguertin commented on ppr-api/src/schemas/search.py
> +    def type_must_match_search_type(cls, search_type):  # pylint:disable=no-self-argument
Created issue #288

2020-01-21 19:25 UTC, WalterMoar approved these changes

2020-01-21 19:29 UTC, gh2os approved these changes

2020-01-21 19:42 UTC, merged