Web client (hello world) with openshift containerization
bcgov/ppr-deprecated pull request #34
Opened 2019-11-21 00:04 UTC by bryan-gilbert

Basic containerization.  Two build images and one Deploy config.  First build the web Vue static pages. Then build an image with a Caddy server that provides these static files.  The deploy config includes a service and route that serves the Vue client on a public url.

2019-11-21 00:32 UTC, jguertin reviewed
Looks good to me.  Comments were discussed in person.

2019-11-21 00:32 UTC, jguertin commented on .gitignore
> +.DS_Store
`.DS_Store` has a duplicate entry

2019-11-22 16:48 UTC, WalterMoar commented on ppr-client/openshift/ppr-ui-bc.tools.yaml
> +        RUN ls -alR /var/www/html
This final RUN command was for debugging. It should be removed.

2019-11-22 16:57 UTC, WalterMoar commented on ppr-client/openshift/ppr-ui-bc.tools.yaml
> +  value: ppr
This doesn't appear to be used in this bc - can you remove it?

2019-11-22 17:01 UTC, WalterMoar commented on ppr-client/openshift/ppr-ui-dc.yaml
> +  value: "2015" #See notes above where this can not be used
I think we're OK hard-coding the port for the dc. Since every pod has its own IP address, we will never have two deploys in the same pod, so no worried about port contention.

While we're on the topic: can we run it on port 8080? It would be nice to have all web servers running on the same port, to reduce "cognitive load".

2019-11-22 17:05 UTC, WalterMoar commented on ppr-client/openshift/ppr-ui-inter-bc.tools.yaml
> +        RUN ls -alR /dist
This looks like another debugging statement that can be removed.

2019-11-22 17:11 UTC, WalterMoar commented on ppr-client/openshift/ppr-ui-dc.yaml
> +  value: zwmtib-tools
GitHub is complaining about no newline at the end, so I guess it can't hurt to put it in.

2019-11-22 19:10 UTC, bryan-gilbert commented on ppr-client/openshift/ppr-ui-dc.yaml
> +  value: "2015" #See notes above where this can not be used
Actually, the default Caddy port is 2015.  We can change this once we add in configuration and volume mounts.  That's a time when having this one-stop location for port will help.

2019-11-22 19:17 UTC, WalterMoar commented on vcli/README.md
> +   - Progressive Web App (PWA) Support
Just to confirm - we're building a SPA that is also a PWA?

2019-11-22 19:18 UTC, WalterMoar requested changes
The big one is that for consistency we probably want this all to be under /ppr-ui, rather than /ppr-client.

2019-11-22 19:21 UTC, WalterMoar commented on ppr-client/openshift/ppr-ui-dc.yaml
> +  value: "2015" #See notes above where this can not be used
OK, looks like all the projects are going with 2015 for any caddy deploys. Since we also want to be consistent with the other teams let's stick with 2015. I think it's better to hard-code for everything, if we have to hard-code for some.

2019-11-22 20:02 UTC, WalterMoar commented
As discussed everything is good for the first pull.

2019-11-22 20:06 UTC, WalterMoar approved these changes

2019-11-22 20:06 UTC, merged