To be reactive the property needs to declared and initialized
bcgov/ppr-deprecated pull request #343
Opened 2020-01-23 19:48 UTC by bryan-gilbert

2020-01-23 20:40 UTC, WalterMoar requested changes
Please remove the two console.log statements.

2020-01-23 20:40 UTC, WalterMoar commented
Can you connect this to the issue?

2020-01-23 20:50 UTC, WalterMoar commented on ppr-ui/src/search/search-serial.ts
> +    this._term = ''
The label should be reactive as well.

2020-01-23 21:56 UTC, bryan-gilbert commented on ppr-ui/src/search/search-serial.ts
> +    this._term = ''
the label contains a static value and does not exist as a private property.

2020-01-24 00:59 UTC, WalterMoar commented on ppr-ui/src/search/search-serial.ts
> +    this._term = ''
Oh yeah - good point.

2020-01-24 01:07 UTC, WalterMoar approved these changes

2020-01-24 21:08 UTC, merged