Sprint 0 Vue client work
bcgov/ppr-deprecated pull request #38
Opened 2019-11-22 23:07 UTC by bryan-gilbert

Move the docs about how to create and update the client into the client folder.
Remove the gitignore file that was generated by the VUE cli. (Depend on the root gitignore)
Fix a unit test.
Add a package.json script to run both the unit and e2e tests.
Typescript use strict mode
Client - add pug, vuetify, do audit fix
npm audit fix
npm install -D pug pug-plain-loader
npm install vuetify
Switch from less to sass/scss to match lear
npm uninstall less
npm uninstall less-loader
npm install -D sass
npm install -D sass-loader
To explain the next install see the sass-loader docs https://www.npmjs.com/package/sass-loader
npm install --save-dev fibers

Import initial styles from lear

Remove generated Vue
Add SBC common headers and footers
npm install sbc-common-components --save

Axios, Configuration, Routes, Auth stub
npm install --save axios

Prefetch configuration
Router and routes
Route hook to check for authorization and redirect if needed

Public vs User page layout templates
BC Reg icons
Initial editor configuration

Create sample dashboard
Create a sample Home page
Create a fake login page
Flow and routing between these.
consistent home and dashboard page layout
code format

2019-11-22 23:20 UTC, WalterMoar commented on ppr-client/src/App.vue
> +            // return false to stop the propagation of errors further to parent or global error handler
We will eventually look at sentry.io here for logging that we can see.

2019-11-22 23:26 UTC, WalterMoar commented on ppr-client/public/config/configuration.json
> +}
Wondering if we want to keep this file and toss the others. It'll be overwritten by a configmap.

2019-11-22 23:32 UTC, WalterMoar commented on ppr-client/.env
> +VUE_APP_PATH = ppr
Save to assume that this file will disappear? We don't usually check in the .env files.

2019-11-22 23:37 UTC, jguertin commented on ppr-client/package.json
> +    "test": "npm run test:e2e && npm run test:e2e",
Seems to be running the tests twice

2019-11-22 23:37 UTC, jguertin commented on ppr-client/public/config/configuration.json
> +  "ADDRESS_COMPLETE_KEY": "RH99-RN99-GB72-FW86"
Should these details be in the source code?

2019-11-22 23:38 UTC, WalterMoar commented on ppr-client/src/App.vue
> +            })
This looks fragile - assume it's from LEAR?

2019-11-22 23:41 UTC, bryan-gilbert commented on ppr-client/.env
> +VUE_APP_PATH = ppr
yes

2019-11-22 23:41 UTC, bryan-gilbert commented on ppr-client/public/config/configuration.json
> +  "ADDRESS_COMPLETE_KEY": "RH99-RN99-GB72-FW86"
will remove address key

2019-11-22 23:42 UTC, bryan-gilbert commented on ppr-client/src/App.vue
> +            })
no -- left over early dev.  Will remove this in next PR

2019-11-22 23:43 UTC, bryan-gilbert commented on ppr-client/package.json
> +    "test": "npm run test:e2e && npm run test:e2e",
Good catch. Will fix in next PR

2019-11-22 23:43 UTC, WalterMoar commented on ppr-client/src/assets/styles/base.scss
> +  font-size: 1rem;
I know this is probably just copied from LEAR but I wonder why not either use the BC font here, or if it doesn't do anything then remove it? CSS is one of those things that is so hard to clean up after the fact :)

2019-11-22 23:44 UTC, WalterMoar commented on ppr-client/src/assets/styles/base.scss
> +  font-family: 'Roboto', sans-serif;
Should be the BC font here, yes?

2019-11-22 23:47 UTC, bryan-gilbert commented on ppr-client/src/assets/styles/base.scss
> +  font-size: 1rem;
This is copied from LEAR.  Can we leave this to a future "sync UI styles with LEAR" user story.

2019-11-22 23:55 UTC, WalterMoar commented on ppr-client/src/registerServiceWorker.ts
> +import {register} from 'register-service-worker'
I'm a bit curious about the formatting. We'll want to use whatever is the default for VS Code. We'll figure that out as we go, though.

2019-11-22 23:58 UTC, WalterMoar commented on ppr-client/src/utils/config-helper.ts
> +    // const url = `/${process.env.VUE_APP_PATH}/config/stub-configuration.json`
I'm fairly keen on not committing commented-out code, but let's just get this monster merged.

2019-11-23 00:10 UTC, WalterMoar commented on ppr-client/tsconfig.json
> +    "strict": false,
This is the only one of real concern for me. If we turn it off now, it will get harder and harder to turn it on.

2019-11-23 00:11 UTC, WalterMoar requested changes
The only change I'd like to see is the TS compiler strict flag. Disabling the checking will cause too much rework with no business benefit, and that's a hard sell.

2019-11-23 00:12 UTC, bryan-gilbert commented on ppr-client/src/registerServiceWorker.ts
> +import {register} from 'register-service-worker'
Me too.  Seeking standardization with automation.

2019-11-23 00:13 UTC, WalterMoar commented on ppr-client/src/assets/styles/base.scss
> +  font-size: 1rem;
I'd like to be careful about building up technical debt. I can't see that kind of thing being approved when there are missing features.

2019-11-23 00:14 UTC, bryan-gilbert commented on ppr-client/tsconfig.json
> +    "strict": false,
This setting was copied from LEAR.  I agree with you and think we should change this back (in the next PR).

2019-11-25 17:21 UTC, WalterMoar approved these changes

2019-11-25 23:07 UTC, merged