#355 Alembic migration script to create collateral tables
bcgov/ppr-deprecated pull request #386
Opened 2020-01-30 19:37 UTC by gh20s

Alembic migration script to create the 3 collateral tables:

- vehicle_type
- vehicle
- general

2020-01-30 19:53 UTC, gh20s commented
Sorry about the closing / opening. I was investigating the "draft pull request" feature. I will not create this much unnecessary noise in further PRs.

2020-01-30 20:13 UTC, WalterMoar approved these changes

2020-01-30 20:15 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +            'vehicle_type.vehicle_type_cd'), nullable=False),
Our allowable line length is 120 characters.  I don't think this would've exceeded that on a single line.

2020-01-30 20:18 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +        sa.Column('reg_number_start', sa.String(length=10), nullable=False),
This should be a FK to `registration.reg_number`

2020-01-30 20:18 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +        sa.Column('reg_number_end', sa.String(length=10)),
This too, should be a FK to `registration.reg_number`

2020-01-30 20:24 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +        'vehicle',
2 more issues with vehicle:
- It needs a PK, even if that's a surrogate, that's fine
- It needs a Foreign Key relationship to `financing_statement`

2020-01-30 20:26 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +        sa.Column('model', sa.String(length=25)),
Is 25 characters a legitimate limitation on Make and Model, or is this simply based on technical constraints in the old system?  We might consider making these `text`.

2020-01-30 20:30 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +        'general',
This table has most of the same issues as 'vehicle', except the Financing Statement FK is present.  Not too sure about the column name `reg_number_fk`, though.  Consider a clearer name, such as `fs_reg_number` or `base_reg_number`.  Personally I would lean towards `base_reg_number` as that's what it's called in `registration`.

2020-01-30 20:30 UTC, jguertin requested changes
A good start, but needs some clean-up on primary and foreign keys

2020-01-30 20:34 UTC, jguertin commented on ppr-api/migrations/versions/34af2f12a9ae_create_collateral_tables.py
> +    op.drop_table('vehicle')
You should drop vehicle before vehicle type because of the foreign key relationship

2020-01-31 19:58 UTC, jguertin approved these changes
Thanks for making those changes

2020-01-31 20:06 UTC, merged