224-Sentry in PPR UI
bcgov/ppr-deprecated pull request #395
Opened 2020-02-01 00:01 UTC by bryan-gilbert

Update how we setup and use Sentry in the UI.
Note that all console.error messages as well as all thrown errors will go to Sentry

2020-02-01 00:20 UTC, jguertin commented on ppr-ui/src/views/SearchPage.vue
> +        .catch((errorMessage: string): void => {
Doesn't catch usually receive an object of type `Error`, rather than `string`?

2020-02-03 17:48 UTC, WalterMoar commented on ppr-ui/src/sentry-helper.ts
> +          new Integrations.CaptureConsole({
Nice! 👍

2020-02-03 17:55 UTC, WalterMoar commented on ppr-ui/src/views/SearchPage.vue
> +        .catch((errorMessage: string): void => {
Oh, that's my fault - I think the type is `any`. You can throw a string, which is what is happening here, but yes the type actually should be `any` and not `string`.

2020-02-03 18:04 UTC, WalterMoar requested changes
We have the other "helpers" in the utils directory, can sentry-helper.ts be moved there too?

That and the type problem Justin pointed out (my fault!) are all that I think it needs.

2020-02-03 18:24 UTC, bryan-gilbert commented on ppr-ui/src/views/SearchPage.vue
> +        .catch((errorMessage: string): void => {
No this is my fault in the way I set up the api calls.  My initial implementation is too complex and it does resolve and reject with a string.  In this case, the catch is getting a string.  The next time I touch these api calls, and now that we have sentry in place, I'll simplify the calls to a single line. (Follow the pattern used in sbc_auth for api calls).

2020-02-03 18:24 UTC, bryan-gilbert commented
> We have the other "helpers" in the utils directory, can sentry-helper.ts be moved there too? 
> That and the type problem Justin pointed out (my fault!) are all that I think it needs.

Good idea to group this with the others.  Thanks

2020-02-03 19:24 UTC, WalterMoar approved these changes

2020-02-03 19:37 UTC, merged