BC and DC configuration files
bcgov/ppr-deprecated pull request #527
Opened 2020-02-19 00:15 UTC by bryan-gilbert

parameter files for build and deploy for PPR-UI

2020-02-19 17:15 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-bc.param
> +# Action: build
What's the difference between component and action?

2020-02-19 17:16 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-bc.yaml
>  - description: The name of the appliction
Typo in "appliction"

2020-02-19 17:17 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-bc.param
> +PPR_GROUP="ppr-ui"
This parameter was removed from the file.

2020-02-19 17:18 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-bc.param
> +PPR_GROUP="ppr-ui"
Nevermind.

2020-02-19 17:21 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-dc.dev.param
> +# Action: build
Again - what is the difference between component and action? Is the action "build"?

2020-02-19 17:22 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-dc.prod.param
> +
GitHub is complaining about the lack of a final newline.

2020-02-19 17:22 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-dc.test.param
> +
GitHub is complaining about the lack of a final newline.

2020-02-21 17:31 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-dc.yaml
> +        "SENTRY_DSN": "https://${SENTRY_KEY}@sentry.io/1834187",
I don't think we should be committing the 1834187. I think we want to be passing in the entire DSN.

2020-02-21 18:25 UTC, bryan-gilbert commented
@WalterMoar both sentry and ld flags have been reset and updated on dev, test and prod.
Have updated the config to use the full sentry url.
Have checked the formatting and the spacing of the dc file is what is desired (so the previous version was not correct).

2020-02-21 19:24 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-inter-bc.param
> +GIT_REF="master"
Might as well go alphabetical on this too.

2020-02-21 19:25 UTC, WalterMoar requested changes
The `ppr-ui-dc.yaml` file has a lot of changes due to formatting. That extra level of indenting should be removed (oops - just saw comment above... jussec)

2020-02-21 21:11 UTC, bryan-gilbert commented
@WalterMoar formatting restored.  For the record the changes came from a activating the Red Hat VSCode YAML extension.

2020-02-21 21:23 UTC, WalterMoar commented on ppr-ui/openshift/ppr-ui-dc.yaml
> +  required: true
This one is out of order :-|

2020-02-21 21:27 UTC, bryan-gilbert commented on ppr-ui/openshift/ppr-ui-dc.yaml
> +  required: true
all in!

2020-02-24 16:13 UTC, WalterMoar approved these changes

2020-02-24 17:30 UTC, merged