Create Financing Statement view
bcgov/ppr-deprecated pull request #550
Opened 2020-02-21 17:01 UTC by bryan-gilbert

To hold the FS component/form

2020-02-21 17:06 UTC, WalterMoar commented on ppr-ui/src/views/Home.vue
> +                  <li v-if="userCanSearch">
Apologies that the Issue wasn't clear - this should be under a NEW feature flag, since this is not search.

2020-02-21 17:09 UTC, WalterMoar commented on ppr-ui/tests/unit/FinancingStatement.spec.ts
> +  })
Safe to assume this is a placeholder test? I'm not sure it's is really testing any functionality, since the component doesn't have any yet...

2020-02-21 17:10 UTC, WalterMoar commented on ppr-ui/tests/unit/FinancingStatement.spec.ts
> +    wrapper = shallowMount(FinancingStatement, { })
Can the empty braces be removed?

2020-02-21 17:11 UTC, WalterMoar requested changes
Looks good, but needs its own feature flag.

2020-02-21 17:14 UTC, bryan-gilbert commented on ppr-ui/src/views/Home.vue
> +                  <li v-if="userCanSearch">
Assumed that all new work will be released with one market feature.  Ought we see if the business needs to manage these as separate features?

2020-02-21 17:15 UTC, bryan-gilbert commented on ppr-ui/tests/unit/FinancingStatement.spec.ts
> +  })
It gives 100% coverage, ;-)

2020-02-21 17:16 UTC, WalterMoar commented on ppr-ui/tests/unit/FinancingStatement.spec.ts
> +  })
Yes, there is that :)

2020-02-21 17:18 UTC, WalterMoar commented on ppr-ui/src/views/Home.vue
> +                  <li v-if="userCanSearch">
No, they're separate features. We can turn both on and off at the same time if that is what the business wants, but if they're combined then we lose the ability to do one or the other, or to open them up to different audiences.

2020-02-21 17:26 UTC, bryan-gilbert commented on ppr-ui/src/views/Home.vue
> +                  <li v-if="userCanSearch">
ok thanks.

2020-02-21 21:38 UTC, bryan-gilbert commented on ppr-ui/tests/unit/FinancingStatement.spec.ts
> +    wrapper = shallowMount(FinancingStatement, { })
no. the tell the component you have empty options.  Without this the tests complain: 
[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
      
      found in
      
      ---> <Anonymous>
             <Root>

2020-02-21 21:38 UTC, bryan-gilbert commented
@WalterMoar feature flag in place

2020-02-24 16:16 UTC, WalterMoar approved these changes

2020-02-24 17:29 UTC, merged