Let Launch Darkly control the feature flags
bcgov/ppr-deprecated pull request #66
Opened 2019-12-09 22:37 UTC by bryan-gilbert

To use MUST set the LD key in the config map in openshift.
Please apply PR #65 first.

2019-12-09 23:30 UTC, bryan-gilbert commented
in progress ... reworking a unit test

2019-12-10 00:23 UTC, WalterMoar commented on ppr-ui/public/config/sample-dev-configuration.json
> +  "LAUNCH_DARKLY_CLIENT_KEY": ""
Can we keep these alphabetical? It makes them easier to scan through to find something.

2019-12-10 00:23 UTC, WalterMoar commented on ppr-ui/src/App.vue
> +  components: { },
Can this line be removed?

2019-12-10 16:59 UTC, WalterMoar commented on ppr-ui/src/flags/feature-flags.ts
> +  private constructor(feature1: boolean = false, feature2: boolean = false) {
I think this is good for now, but I can see it being a problem when we a lot of flags. Is VueX not an option?

2019-12-10 17:50 UTC, bryan-gilbert commented on ppr-ui/src/flags/feature-flags.ts
> +  private constructor(feature1: boolean = false, feature2: boolean = false) {
Exactly.  This was a design decision that we need to revisit.  The current assumption is we'll not have very many flags (under 10) in play at any time. We can pause and reconsider this assumption now or push that out to a later time.  Open to guidance here.

2019-12-10 18:50 UTC, WalterMoar commented on ppr-ui/src/flags/feature-flags.ts
> +  private constructor(feature1: boolean = false, feature2: boolean = false) {
It's definitely not something to worry about for this PR but something good to sort out soon. Wish I had guidance but let's keep pondering :)

2019-12-10 18:51 UTC, WalterMoar commented on ppr-ui/public/config/configuration.json
> +  "LAUNCH_DARKLY_CLIENT_KEY": "Client side ID from https://app.launchdarkly.com/settings/projects"
I guess we should alphabetize these for consistency.

2019-12-10 18:51 UTC, jguertin commented on ppr-ui/src/flags/feature-flags.ts
> +  private constructor(feature1: boolean = false, feature2: boolean = false) {
I would imagine we'll end up taking a data structure rather than a bunch of individual components, so I vote cross the bridge when we get there.

2019-12-10 19:37 UTC, WalterMoar requested changes
Just the minor change to ppr-ui/public/config/configuration.json and then it's good to go.

2019-12-10 20:47 UTC, jguertin requested changes

2019-12-10 20:47 UTC, jguertin commented on ppr-ui/src/utils/config-helper.ts
> +    if(debug) console.log('Fetch config from ', url)
Generally speaking, we should avoid committing `console.log()`.  If you do want debugging to be always be performed in the client, you can use `console.debug()` (without `if (debug)`).  You can then adjust the logs you view with the in browser tools.

2019-12-10 20:47 UTC, jguertin commented on ppr-ui/src/flags/ld-user.ts
> +  // return a LDUser ... defined in https://github.com/launchdarkly/js-sdk-common/blob/master/typings.d.ts
I'm assuming commented code will be removed quickly?

2019-12-10 21:19 UTC, WalterMoar approved these changes

2019-12-10 21:22 UTC, merged