Base Party #642 - Functional
bcgov/ppr-deprecated pull request #725
Opened 2020-03-09 23:09 UTC by bryan-gilbert

Does not include UX styling. 
Also #647 since Secured Party is exactly the same as Base Party.
Update BusinessName component to follow unit test element id pattern.
Rename BusinessModel test to match the component: BusinessName.

2020-03-10 15:19 UTC, WalterMoar commented on ppr-ui/src/base-party/BaseParty.vue
> +    <v-form @input="formValid($event)">
FYI, I think a shortcut for `func($event)` is `func`.

2020-03-10 15:22 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> +  businessName: BusinessInterface;
Thoughts on the difference in naming here? Should the variable name be "business", if it represents more than just a name? Or should the interface be `BusinessNameInterface` if it never will be extended beyond the name?

2020-03-10 15:23 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> +–   * Class declarations
Not sure how this dash snuck in there :)

2020-03-10 15:28 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> + * The model for a party name, such as for a registering party.
I think this comment is out of date now.

2020-03-10 15:28 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> + * The interface to a party name.
I think this comment is out of date now.

2020-03-10 15:29 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> +  public get businessName(): BusinessModel {
I've been adding comments for all public methods, since the IDE uses it for mouse-over hints (I realize that these are sort of self-explanatory).

2020-03-10 15:32 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> +  public static fromJson(jsonObject: BasePartyInterface): BasePartyModel {
Philosophically speaking, I'm wondering if the `fromJson` methods should handle `undefined` as their parameter. It could greatly simplify things down the road, as the models become more and more complex. Something to ponder / refactor later.

2020-03-10 15:34 UTC, WalterMoar commented on ppr-ui/src/base-party/BaseParty.vue
> +    // Callback function for emitting Person validity back to the parent.
This comment: it is now Person _or Business_ validity, yes?

2020-03-10 15:36 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BaseParty.spec.ts
> +    })
The only difference here is the inclusion of vuetify. What does that affect?

2020-03-10 15:38 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BaseParty.spec.ts
> +      expect(element).toBeDefined()
Isn't this `expect(wrapper.get('[data-test-id="BaseParty.radio.business"]')).toBeDefined()`? Or is the underlying HTML element significant?

2020-03-10 15:40 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BaseParty.spec.ts
> +      expect(wrapper.find('[data-test-id="BaseParty.radio.person"]').exists()).toBeFalsy()
Again - why the different tests for HTML element to be defined vs. vue component to exist?

2020-03-10 15:43 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BusinessName.spec.ts
> +import Vue from 'vue'
A lot of comments about the BusinessModel are applicable here too.

2020-03-10 15:44 UTC, WalterMoar commented on ppr-ui/tests/unit/components/base-party-model.spec.ts
> +    const aBusiness = 'a person'
Might want to have a different string here.

2020-03-10 15:46 UTC, WalterMoar requested changes
Some changes requested - I'm not understanding some of the testing.

2020-03-10 16:05 UTC, bryan-gilbert commented on ppr-ui/tests/unit/components/BaseParty.spec.ts
> +    })
I started to include vuetify to mimic the unit tests you submitted.  Sometimes it is not needed if the component and all of its children are basic dom elements. It is needed, i think, if any element is a vuetify element.  Do you think it'd be easier to just include it in component tests?

2020-03-10 16:05 UTC, bryan-gilbert commented on ppr-ui/src/base-party/BaseParty.vue
> +    <v-form @input="formValid($event)">
Which do you prefer?  I prefer long paths because they don't make me think as much.

2020-03-10 16:06 UTC, bryan-gilbert commented on ppr-ui/src/base-party/base-party-model.ts
> +  businessName: BusinessInterface;
Yes.  BusinessNameInterface is better.

2020-03-10 17:53 UTC, WalterMoar commented on ppr-ui/src/base-party/BaseParty.vue
> +    <v-form @input="formValid($event)">
Agreed (although I was originally in the other camp - but it does make it look like a function, and the IDE styles it in a different colour).

2020-03-10 17:55 UTC, WalterMoar commented on ppr-ui/src/base-party/base-party-model.ts
> +  private _businessName: BusinessModel
So I hate to ask - for consistency, is it a BusinessNameModel?

2020-03-10 17:57 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BaseParty.spec.ts
> +// import { PersonNameModel } from '@/components/person-name-model'
This commented out code should be removed.

2020-03-10 17:59 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BaseParty.spec.ts
> +    })
Can you delete the test on lines 35-40? It looks to be identical to the 28-33 test, except that it doesn't include vuetify.

2020-03-10 18:02 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BusinessName.spec.ts
> +      const expected = 'business Name'
There is not test for `expected` - is it missing?

2020-03-10 18:04 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BusinessName.spec.ts
> +})
Do you need tests for the "valid" event? I'm definitely missing them in my code!

2020-03-10 20:07 UTC, bryan-gilbert commented on ppr-ui/tests/unit/components/BusinessName.spec.ts
> +      const expected = 'business Name'
thanks

2020-03-10 20:08 UTC, bryan-gilbert commented on ppr-ui/tests/unit/components/BusinessName.spec.ts
> +import Vue from 'vue'
Did the recommits catch these comments?

2020-03-10 23:03 UTC, WalterMoar commented on ppr-ui/tests/unit/components/BusinessName.spec.ts
> +    })
These two tests are the same.

2020-03-11 19:41 UTC, bryan-gilbert commented
https://github.com/bcgov/ppr/pull/739 replaces this PR

2020-03-11 19:41 UTC, closed without merging