Add a "Health Check" endpoint for readiness probes to call on OpenShift
bcgov/ppr-deprecated pull request #73
Opened 2019-12-13 00:05 UTC by jguertin

2019-12-13 00:33 UTC, bryan-gilbert reviewed
nice and simple

2019-12-13 00:34 UTC, bryan-gilbert approved these changes

2019-12-16 16:38 UTC, WalterMoar commented on ppr-api/src/endpoints/healthcheck.py
> +router = APIRouter()
I'd like to go with more explicit calls to module functions:

```python
import fastapi

router.fastapi.APIRouter()
```

2019-12-16 16:39 UTC, WalterMoar commented on ppr-api/src/main.py
> +app.include_router(healthcheck.router)
I'm going to change this when I fix my merge conflicts.

2019-12-16 16:42 UTC, jguertin commented on ppr-api/src/endpoints/healthcheck.py
> +router = APIRouter()
sure

2019-12-16 16:43 UTC, WalterMoar commented on ppr-api/src/endpoints/healthcheck.py
> +@router.get("/health", include_in_schema=False)
We should include this in the OpenAPI endpoint - we won't expose it through the gateway, but it saves digging in the code when we want to find the check.

When I fix my merge conflicts I'll separate it out in the docs.

2019-12-16 16:45 UTC, WalterMoar requested changes
One change with module conventions and readability, to always explicitly use the module name.

2019-12-16 17:07 UTC, jguertin commented on ppr-api/src/main.py
> +app.include_router(healthcheck.router)
👍

2019-12-16 17:08 UTC, jguertin commented on ppr-api/src/endpoints/healthcheck.py
> +@router.get("/health", include_in_schema=False)
Sure, if you can separate it out from the docs that's great.  I've removed the flag.

2019-12-16 17:15 UTC, WalterMoar approved these changes

2019-12-16 17:30 UTC, WalterMoar commented
Gonna merge this so I can grab it.

2019-12-16 17:30 UTC, merged