Search Serial number 10 second version
bcgov/ppr-deprecated pull request #83
Opened 2019-12-17 22:10 UTC by bryan-gilbert

with a LoadIndictor component

2019-12-17 22:23 UTC, jguertin commented on ppr-ui/src/load-indicator/LoadIndicator.vue
> +        <!--</div>-->
Please remove commented code

2019-12-18 00:00 UTC, bryan-gilbert commented on ppr-ui/src/load-indicator/LoadIndicator.vue
> +        <!--</div>-->
would like to keep this comment pending UX

2019-12-18 06:32 UTC, jguertin requested changes
It feels good to see working code for searching, this is a huge milestone, great work!  I have a few small requests for changes, the main one being around the use of console.log.  The rest is really just questions, and can probably be resolved with a quick discussion.

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/load-indicator/index.ts
> +    console.log('start')
I see a few `console.log()` calls in here.  If you want to keep them, transition to `console.debug()` as we discussed, as well as provide a bit more context.

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/load-indicator/index.ts
> +  }
Was reflecting on our conversation from earlier, good chat.  Except for the singleton instance, I like how this class is structured and the functionality it encapsulates.  I've got an idea to bounce off of you to harness that power, let's have a quick chat in the morning and you can let me know what you think.

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/router/router.ts
> +  if (ENABLED) {
Is this just to temporarily  hide this functionality until we're ready to use it?

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/search/SearchResultsSerial.vue
> +            :key="item.name"
This might be a TS newbie question, does the SerialResult class have a `name` property?

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/search/search-serial.ts
> +        .get(url, {headers})
Not a huge issue in this case but I believe you can optionally use `params: {serial: term}`. Can save us hard-coding  `?search=` and other parameters in the URL, and I assume handle url encoding.

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/views/results-page.vue
> +<template>
Did you intend to commit this file?  It seems to be superseded by your work above, and the filename doesn't match the conventions of your other `.vue` files.

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/views/search-page.vue
> +<template>
Same question as `results-page.vue`

2019-12-18 06:32 UTC, jguertin commented on ppr-ui/src/search/search-serial.ts
> +  }
similar to our earlier discussion, I'm not sure a singleton instance is the right fit for this data type.

2019-12-18 16:42 UTC, jguertin commented on ppr-ui/src/search/search-serial.ts
> +      , (value): (boolean | string) => { return /^\d{4}$/.test(value) || 'serial number must be 4 digits' }
I'm assuming this is here for demonstrable purposes?  It can actually be an alpha-numeric up to 25 characters.

2019-12-18 18:27 UTC, WalterMoar approved these changes
I'm onboard with shipping this as-is, and then doing a code review to learn about the details.

2019-12-18 18:51 UTC, bryan-gilbert commented on ppr-ui/src/load-indicator/index.ts
> +    console.log('start')
will address in a separate pr

2019-12-18 18:52 UTC, bryan-gilbert commented on ppr-ui/src/load-indicator/index.ts
> +  }
will address in a separate PR

2019-12-18 18:52 UTC, bryan-gilbert commented on ppr-ui/src/router/router.ts
> +  if (ENABLED) {
yes

2019-12-18 18:56 UTC, bryan-gilbert commented on ppr-ui/src/search/SearchResultsSerial.vue
> +            :key="item.name"
Vue components can have a name property. But this introduces a potential for misnaming. A Vue component' name defaults to file name (hence the convention to use Pascal case).  If a developer also provides an explicit name property this takes precedence.  This is fine until another developer copies a component and forgets to manually edit the name property (very easy to do).  What happens then is the newly copied component retains the original name when viewed in debugger.   I can not think of any reason to provide an explicit name and recommend we avoid this pattern and let Vue default to the file name.

2019-12-18 18:56 UTC, bryan-gilbert commented on ppr-ui/src/search/search-serial.ts
> +        .get(url, {headers})
good idea.  Will create an issue to track this and will address in another PR

2019-12-18 18:58 UTC, bryan-gilbert commented on ppr-ui/src/views/results-page.vue
> +<template>
yes this is the page that contains components that display results.  In a separate PR I will correct the file naming to follow our conventions.

2019-12-18 18:58 UTC, bryan-gilbert commented on ppr-ui/src/views/search-page.vue
> +<template>
ditto

2019-12-18 18:58 UTC, bryan-gilbert commented on ppr-ui/src/search/search-serial.ts
> +  }
as per our discussion ... will address in a later PR

2019-12-18 18:59 UTC, bryan-gilbert commented on ppr-ui/src/search/search-serial.ts
> +      , (value): (boolean | string) => { return /^\d{4}$/.test(value) || 'serial number must be 4 digits' }
the second test is a placeholder, example, to demonstrate validation.  We can correct this in a smaller PR

2019-12-18 19:02 UTC, jguertin commented on ppr-ui/src/search/SearchResultsSerial.vue
> +            :key="item.name"
item isn't a Vue component, though.  It's an instance pf `SerialResult`.

2019-12-18 19:06 UTC, jguertin approved these changes
Approved, with the understanding of changes being addressed downstream

2019-12-18 19:07 UTC, merged