Add Validation to Name Fields
bcgov/ppr-deprecated pull request #859
Opened 2020-03-20 22:29 UTC by gh20s

First past at adding some validation to the Party Schema:

- personName is alphabetical other than hyphen ( - ) or apostrophe ( ' )

- businessName is alphanumeric plus allows the following special characters: & ' : , $ - ( ) % . + " " ; /

- Party cannot have businessName and personName

Also added basic tests for IndividualName and Address classes

2020-03-20 22:37 UTC, WalterMoar commented on ppr-api/src/schemas/party.py
> +        assert re.match("^[a-zA-Z-']*$", v), '"IndividualName" contains invalid character'
Does this RE allow spaces for, say, Chris De Burgh?

2020-03-20 22:42 UTC, bryan-gilbert requested changes
Looks good.  I'm requesting some small changes. Let me know if you disagree and I'll approve.

2020-03-20 22:42 UTC, bryan-gilbert commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +
might be good to make three tests.  This will test the first name validation and not the middle nor last.  Right?

2020-03-20 22:42 UTC, bryan-gilbert commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +    assert name.businessName == 'Aa-\'"&:,$%.+;/zZ1234567890 '
Good test.  Do you want to add two tests like this for first and last person name.

2020-03-20 22:42 UTC, bryan-gilbert commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +    except ValueError:
no postal .. what is address is outside Canada?

2020-03-20 22:43 UTC, gh20s commented on ppr-api/src/schemas/party.py
> +        assert re.match("^[a-zA-Z-']*$", v), '"IndividualName" contains invalid character'
This one does not - businessName does, I will check with whomever is the expert on that one. I wasn't told to include spaces, but they weren't  explicit in excluding them.

2020-03-20 22:45 UTC, jguertin commented on ppr-api/src/schemas/party.py
> +        assert re.match('^[a-zA-Z-0-9-\'"&:,$%.+;/ ]*$', v), '"businessName" contains invalid character'
You actually have `-` in here twice.  I'm not sure about the error message, it's not quite sure if it's dealing with singular or multiple ;). In all seriousness, it might be valuable to inform the caller what characters are valid.

2020-03-20 22:48 UTC, gh20s commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +
I originally had three tests as well, but I am somewhat confident (but not 100%) that the validator checks all fields ('*')? I understand it to checks each individual value. I may have misunderstood something when reading up on it. Either way, I'm happy to add 2 more.

2020-03-20 22:49 UTC, gh20s commented on ppr-api/src/schemas/party.py
> +        assert re.match('^[a-zA-Z-0-9-\'"&:,$%.+;/ ]*$', v), '"businessName" contains invalid character'
I had it much longer before, I can never tell what's good practice. Happy to add it back in there.

2020-03-20 22:53 UTC, gh20s commented on ppr-api/src/schemas/party.py
> +        assert re.match('^[a-zA-Z-0-9-\'"&:,$%.+;/ ]*$', v), '"businessName" contains invalid character'
also good catch on the hyphen, thanks :)

2020-03-20 22:59 UTC, jguertin requested changes
Good work, but tests need to be corrected.  Would prefer a bit more detailed messaging, but will leave that to you.

2020-03-20 22:59 UTC, jguertin commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +        schemas.party.IndividualName(personName={'first': 'John Doe'})
I don't think this is throwing a ValueError for the reason you think it should.  personName isn't a field on IndividualName.  Should be `schemas.party.IndividualName(first='John Doe')`

Same applies to the next 4 tests

2020-03-20 22:59 UTC, jguertin commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +    assert name.businessName == 'Aa-\'"&:,$%.+;/zZ1234567890 '
Here's a question for you: should we trim whitespace from the beginning and end of a string? I don't know the answer, I'm just asking.

2020-03-20 23:01 UTC, jguertin commented on ppr-api/src/schemas/party.py
> +        assert re.match('^[a-zA-Z-0-9-\'"&:,$%.+;/ ]*$', v), '"businessName" contains invalid character'
Longer is okay, but it can be tough as someone debugging the system to determine which characters on their input were invalid.

2020-03-20 23:05 UTC, gh20s commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +        schemas.party.IndividualName(personName={'first': 'John Doe'})
Yeah thanks for that, I originally had it testing schemas.party.Debtor(personName={} ) but changed it to the above, but not fully clearly. I think it was better off if I didn't try and push this off before the end of the day and came at it with fresh eyes :)

2020-03-20 23:16 UTC, jguertin commented on ppr-api/tests/unit/schemas/test_party_schema.py
> +
Certainly a valid point, best to get each field failing independently

2020-03-20 23:18 UTC, jguertin commented on ppr-api/src/schemas/party.py
> +        assert re.match("^[a-zA-Z- ']*$", v), '"IndividualName" contains invalid character'
I should've been specific, sorry. Should probably update both error messages.

2020-04-01 16:07 UTC, jguertin commented
Closing, as it will not be completed

2020-04-01 16:07 UTC, closed without merging